## ***Домашняя работа №1***

***Данная работа посвящена введению в основы работы с библиотекой NumPy для вычислений в Python. Будут рассмотрены ключевые операции с массивами: создание, изучение свойств, индексирование и математические операции.***

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [3]:
zeros_arr = np.zeros(5)
ones_arr = np.ones((3, 2))
range_arr = np.arange(20, 3)

zeros_arr, ones_arr, range_arr

(array([0., 0., 0., 0., 0.]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([], dtype=int32))

In [4]:
print("Массив:", arr)
print("Форма массива:", arr.shape)
print("Тип данных массива:", arr.dtype)
print("Расзмерность массива:", arr.ndim)

Массив: [1 2 3 4 5]
Форма массива: (5,)
Тип данных массива: int32
Расзмерность массива: 1


In [5]:
# Создание двумерного массива
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Исходная матрица:", *matrix, sep="\n")

# Получение отдельного элемента (вторая строка, третий столбец)
element = matrix[1, 2]
print("\nЭлемент:", element)

# Извлечение подмассива с помощью среза (первые две строки, два столбца). Строки: 0-1, столбцы: 1-2
submatrix = matrix[:2, 1:]  
print("\nПодмассив:", *submatrix, sep="\n")

Исходная матрица:
[1 2 3]
[4 5 6]
[7 8 9]

Элемент: 6

Подмассив:
[2 3]
[5 6]


In [6]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

sum_arrays = arr1 + arr2
print("Массив после поэлементного сложения: ", sum_arrays)

mult_arrays = arr1 * arr2
print("Массив после поэлементного умножения:", mult_arrays)

# Вычисление статистических показателей
data = np.array([2, 4, 6, 8, 10])
print("\nСтатистика для массива:", data)
print("Среднее значение:", np.mean(data))
print("Стандартное отклонение:", np.std(data))
print("Максимальное значение:", np.max(data))
print("Минимальное значение:", np.min(data))
print("Сумма всех элементов:", np.sum(data))

Массив после поэлементного сложения:  [ 6  8 10 12]
Массив после поэлементного умножения: [ 5 12 21 32]

Статистика для массива: [ 2  4  6  8 10]
Среднее значение: 6.0
Стандартное отклонение: 2.8284271247461903
Максимальное значение: 10
Минимальное значение: 2
Сумма всех элементов: 30


In [7]:
arr = np.array([2, 4, 6, 8, 10])
print(f"Исходный массив: {arr}\n")

mean = np.sum(arr) / arr.size
print(f"Среднее значение: {mean}")

squared_deviations = (arr - mean) ** 2
print(f"Квадраты отклонений: {squared_deviations}")

variance = np.sum(squared_deviations) / arr.size
print(f"Дисперсия: {variance}")

std_dev = np.sqrt(variance)
print(f"\nСравнение результатов:\n{std_dev} - рассчитаное значение\n{np.std(arr)} - значение, полученное с помощью встроенной функции")

Исходный массив: [ 2  4  6  8 10]

Среднее значение: 6.0
Квадраты отклонений: [16.  4.  0.  4. 16.]
Дисперсия: 8.0

Сравнение результатов:
2.8284271247461903 - рассчитаное значение
2.8284271247461903 - значение, полученное с помощью встроенной функции
